version: "3.8" # Versi Docker Compose

services:
    db:
        image: postgres:alpine3.18
        container_name: postgres_container
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build: .
        container_name: be-project-app
        restart: always
        ports:
            - "8080:8080"
        environment:
            APP_DSN: ${APP_DSN}
            APP_PORT: ${APP_PORT}
            APP_SEED_USERNAME: ${APP_SEED_USERNAME}
            APP_SEED_PASSWORD: ${APP_SEED_PASSWORD}
            APP_SEED_EMAIL: ${APP_SEED_EMAIL}

        depends_on:
            db:
                condition: service_healthy

volumes:
    postgres_data:

networks:
    postgres_network: # Jaringan internal untuk container
        driver: bridge
